// Generated by CoffeeScript 1.12.2
(function() {
  var key, ref, ref1, val;

  exports.EncodeStream = require('./src/EncodeStream');

  exports.DecodeStream = require('./src/DecodeStream');

  exports.Array = require('./src/Array');

  exports.LazyArray = require('./src/LazyArray');

  exports.Bitfield = require('./src/Bitfield');

  exports.Boolean = require('./src/Boolean');

  exports.Buffer = require('./src/Buffer');

  exports.Enum = require('./src/Enum');

  exports.Optional = require('./src/Optional');

  exports.Reserved = require('./src/Reserved');

  exports.String = require('./src/String');

  exports.Struct = require('./src/Struct');

  exports.VersionedStruct = require('./src/VersionedStruct');

  ref = require('./src/Number');
  for (key in ref) {
    val = ref[key];
    exports[key] = val;
  }

  ref1 = require('./src/Pointer');
  for (key in ref1) {
    val = ref1[key];
    exports[key] = val;
  }

}).call(this);
