// Generated by CoffeeScript 1.12.2
(function() {
  var Bitfield;

  Bitfield = (function() {
    function Bitfield(type, flags) {
      this.type = type;
      this.flags = flags != null ? flags : [];
    }

    Bitfield.prototype.decode = function(stream) {
      var flag, i, j, len, ref, res, val;
      val = this.type.decode(stream);
      res = {};
      ref = this.flags;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        flag = ref[i];
        if (flag != null) {
          res[flag] = !!(val & (1 << i));
        }
      }
      return res;
    };

    Bitfield.prototype.size = function() {
      return this.type.size();
    };

    Bitfield.prototype.encode = function(stream, keys) {
      var flag, i, j, len, ref, val;
      val = 0;
      ref = this.flags;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        flag = ref[i];
        if (flag != null) {
          if (keys[flag]) {
            val |= 1 << i;
          }
        }
      }
      return this.type.encode(stream, val);
    };

    return Bitfield;

  })();

  module.exports = Bitfield;

}).call(this);
